/**
 * DEPRECATED: Prefer importing from '@/styles/designTokens' instead.
 * Backward-compatible aliases to the new light theme design tokens.
 */
export * from './designTokens';

export const adminStyles = {
  container: 'min-h-screen bg-white',
  pageContainer: 'max-w-7xl mx-auto px-6 py-8',
  cardContainer: 'bg-white border border-gray-200 rounded-lg',
  sectionHeader: 'text-2xl font-bold text-[#1a1a2e] mb-6 flex items-center gap-3',
  sectionSubtitle: 'text-gray-500 text-sm',
  card: 'bg-white border border-gray-200 rounded-lg p-6 hover:border-gray-300 transition-colors',
  cardWithHover: 'bg-white border border-gray-200 rounded-lg p-6 hover:border-[#0071c2] hover:shadow-md transition-all',
  table: 'w-full',
  tableHeader: 'bg-[#f2f6fc] border-b border-gray-200',
  tableHeaderCell: 'px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider',
  tableRow: 'border-b border-gray-100 hover:bg-[#f2f6fc] transition-colors',
  tableCell: 'px-6 py-4 text-sm text-[#1a1a2e]',
  tableCellIcon: 'flex items-center gap-2',
  btnPrimary: 'bg-[#0071c2] hover:bg-[#005999] text-white px-4 py-2 rounded-md font-medium transition-all',
  btnDanger: 'bg-[#cc0000] hover:bg-[#aa0000] text-white px-4 py-2 rounded-md font-medium transition-all',
  btnSecondary: 'border border-[#0071c2] text-[#0071c2] hover:bg-[#ebf3ff] px-4 py-2 rounded-md font-medium transition-all bg-white',
  btnSuccess: 'bg-[#008009] hover:bg-[#006600] text-white px-4 py-2 rounded-md font-medium transition-all',
  btnWarning: 'bg-[#b95000] hover:bg-[#9a4000] text-white px-4 py-2 rounded-md font-medium transition-all',
  btnSmall: 'px-2.5 py-1.5 text-xs',
  btnCancel: 'border border-gray-200 text-gray-600 hover:border-gray-300 px-4 py-2 rounded-md font-medium transition-all bg-white',
  filterContainer: 'bg-white border border-gray-200 rounded-lg p-6',
  filterGrid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4',
  badgeSuccess: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-[#ebf7eb] text-[#008009]',
  badgeWarning: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-[#fff3e0] text-[#b95000]',
  badgeDanger: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-[#fff0f0] text-[#cc0000]',
  badgeInfo: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-[#ebf3ff] text-[#0071c2]',
  badgeNeutral: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold bg-gray-100 text-gray-600',
  badge: 'inline-flex px-2.5 py-1 rounded-full text-xs font-semibold',
  modal: 'fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4',
  modalContent: 'bg-white border border-gray-200 rounded-lg max-w-lg w-full shadow-xl',
  modalHeader: 'px-6 py-4 border-b border-gray-100',
  modalTitle: 'text-lg font-semibold text-[#1a1a2e]',
  modalBody: 'px-6 py-6 space-y-4 max-h-[70vh] overflow-y-auto',
  modalFooter: 'px-6 py-4 border-t border-gray-100 flex justify-end gap-3',
  input: 'w-full px-4 py-2.5 bg-white border border-gray-200 rounded-md text-[#1a1a2e] placeholder-gray-400 focus:outline-none focus:border-[#0071c2] focus:ring-2 focus:ring-[#0071c2]/20 transition-colors text-sm',
  inputLabel: 'block text-sm font-medium text-gray-600 mb-1.5',
  label: 'block text-sm font-medium text-gray-600 mb-1.5',
  select: 'w-full px-4 py-2.5 bg-white border border-gray-200 rounded-md text-[#1a1a2e] focus:outline-none focus:border-[#0071c2] focus:ring-2 focus:ring-[#0071c2]/20 transition-colors text-sm appearance-none cursor-pointer',
  loadingSpinner: 'inline-block animate-spin rounded-full h-8 w-8 border-2 border-gray-200 border-t-[#0071c2]',
  alertError: 'bg-[#fff0f0] border border-[#f5c6c6] text-[#cc0000] rounded-md p-4 text-sm',
  alertSuccess: 'bg-[#ebf7eb] border border-[#c3e6c3] text-[#008009] rounded-md p-4 text-sm',
  emptyState: 'text-center py-12 px-6 bg-white rounded-lg border border-gray-200',
  emptyStateIcon: 'text-5xl mb-4 opacity-40',
  emptyStateText: 'text-gray-500',
  formGroup: 'space-y-2',
  paginationBtn: 'px-3 py-2 rounded-md border border-gray-200 hover:border-[#0071c2] transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm text-gray-600',
};

export const statusColors: Record<string, { bg: string; border: string; text: string }> = {
  PENDING: { bg: 'bg-[#fff3e0]', border: 'border-[#f5d6a3]', text: 'text-[#b95000]' },
  PENDING_REVIEW: { bg: 'bg-[#fff3e0]', border: 'border-[#f5d6a3]', text: 'text-[#b95000]' },
  APPROVED: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  ACTIVE: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  REJECTED: { bg: 'bg-[#fff0f0]', border: 'border-[#f5c6c6]', text: 'text-[#cc0000]' },
  DEACTIVATED: { bg: 'bg-[#fff0f0]', border: 'border-[#f5c6c6]', text: 'text-[#cc0000]' },
  INACTIVE: { bg: 'bg-gray-100', border: 'border-gray-200', text: 'text-gray-500' },
  COMPLETED: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  CANCELLED: { bg: 'bg-[#fff0f0]', border: 'border-[#f5c6c6]', text: 'text-[#cc0000]' },
  DISPUTED: { bg: 'bg-[#fff3e0]', border: 'border-[#f5d6a3]', text: 'text-[#b95000]' },
  VERIFIED: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  UNVERIFIED: { bg: 'bg-gray-100', border: 'border-gray-200', text: 'text-gray-500' },
  CONFIRMED: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  EXPIRED: { bg: 'bg-gray-100', border: 'border-gray-200', text: 'text-gray-500' },
  REFUNDED: { bg: 'bg-[#ebf3ff]', border: 'border-[#b3d4f5]', text: 'text-[#0071c2]' },
  RESOLVED: { bg: 'bg-[#ebf7eb]', border: 'border-[#c3e6c3]', text: 'text-[#008009]' },
  IN_PROGRESS: { bg: 'bg-[#fff3e0]', border: 'border-[#f5d6a3]', text: 'text-[#b95000]' },
  OPEN: { bg: 'bg-[#ebf3ff]', border: 'border-[#b3d4f5]', text: 'text-[#0071c2]' },
  DISMISSED: { bg: 'bg-gray-100', border: 'border-gray-200', text: 'text-gray-500' },
};
